name: Nodejs and Next.js CI/CD for OstroHub

on: 
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build_and_test:
    runs-on: ubuntu-latest  # Use dash instead of underscore for runs-on

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run ESLint
      - name: Run ESLint
        run: npm run lint

      # Build the project
      - name: Build frontend
        run: npm run build
